services:
  web:
    build:
      context: .
    container_name: queen-victoria-web
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - app_data:/app/data
      - staticfiles:/app/staticfiles
    restart: unless-stopped

volumes:
  app_data:
  staticfiles:
