# Generated by Django 6.0.3 on 2026-04-02 14:44

import django.core.validators
import django.db.models.deletion
import pages.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Folder arhiva',
                'verbose_name_plural': 'Foldere arhiva',
                'ordering': ['sort_order', '-name'],
            },
        ),
        migrations.CreateModel(
            name='ArchiveDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('file', models.FileField(upload_to=pages.models.archive_document_upload_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Fisier PDF')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='pages.archivefolder', verbose_name='Folder')),
            ],
            options={
                'verbose_name': 'Document arhiva',
                'verbose_name_plural': 'Documente arhiva',
                'ordering': ['sort_order', 'title', 'file'],
            },
        ),
    ]
