# Generated by Django 6.0.3 on 2026-04-02 17:38

import django.core.validators
import django.db.models.deletion
import pages.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtapaConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Etapa')),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Etapa (configurare)',
                'verbose_name_plural': 'Etape (configurare)',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='JudetConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Judet')),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Judet (configurare)',
                'verbose_name_plural': 'Judete (configurare)',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RezultateEtapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Etapa')),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Etapa rezultate',
                'verbose_name_plural': 'Etape rezultate',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RezultateJudet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Judet')),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Judet rezultate',
                'verbose_name_plural': 'Judete rezultate',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RezultateYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='An')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'An rezultate',
                'verbose_name_plural': 'Ani rezultate',
                'ordering': ['sort_order', '-name'],
            },
        ),
        migrations.CreateModel(
            name='RezultateDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Titlu')),
                ('file', models.FileField(upload_to=pages.models.rezultate_document_upload_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Fisier PDF')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='pages.rezultateetapa', verbose_name='Etapa')),
            ],
            options={
                'verbose_name': 'Document rezultate',
                'verbose_name_plural': 'Documente rezultate',
                'ordering': ['sort_order', 'title', 'file'],
            },
        ),
        migrations.AddField(
            model_name='rezultateetapa',
            name='judet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etape', to='pages.rezultatejudet', verbose_name='Judet'),
        ),
        migrations.AddField(
            model_name='rezultatejudet',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judete', to='pages.rezultateyear', verbose_name='An'),
        ),
        migrations.AlterUniqueTogether(
            name='rezultateetapa',
            unique_together={('judet', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='rezultatejudet',
            unique_together={('year', 'name')},
        ),
    ]
